default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

local: &local
  <<: *default
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: mephisto_development

test:
  <<: *default
  database: mephisto_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
